#!/usr/bin/env python3
"""Render human and agent projections from ProductIntentModel without creating new authority."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def _line(value):
    return str(value or "").strip()


def render_behavior(model: dict) -> str:
    product = model["product"]
    lines = [
        f"# {product.get('title') or 'Product'} — intended behavior",
        "",
        "> Generated from ProductIntentModel. This is a projection, not a source of truth.",
        "",
        "## Problem",
    ]
    lines += [f"- {item}" for item in product.get("problem", [])] or ["- Not recorded."]
    lines += ["", "## Intended outcome"]
    lines += [f"- {item}" for item in product.get("outcome", [])] or ["- Not recorded."]
    lines += ["", "## Capabilities"]
    for cap in model.get("selected_design", {}).get("capabilities", []):
        lines.append(f"- **{cap['id']}** — {cap.get('statement', '')}")
    if not model.get("selected_design", {}).get("capabilities"):
        lines.append("- None explicitly recorded.")
    lines += ["", "## Requirements"]
    for req in model.get("requirements", []):
        lines.append(f"- **{req['id']}** — {req.get('statement', '')}")
    lines += ["", "## Decisions"]
    for decision in model.get("decisions", []):
        rejected = ", ".join(decision.get("rejected", [])) or "none recorded"
        why = "; ".join(decision.get("rationale", [])) or "reason not recorded"
        lines.append(
            f"- **{decision['id']}** — selected {decision.get('selected') or '—'}; "
            f"rejected {rejected}. Why: {why}."
        )
        if decision.get("reopen_when"):
            lines.append(f"  Reopen when: {decision['reopen_when']}")
    lines += ["", "## Product invariants"]
    for inv in model.get("invariants", []):
        lines.append(f"- **{inv['id']} [{inv.get('severity', 'must')}]** — {inv.get('statement', '')}")
    if not model.get("invariants"):
        lines.append("- None explicitly recorded.")
    lines += ["", "## Representative behavior"]
    for trace in model.get("selected_design", {}).get("behavior_traces", []):
        scenario = _line(trace.get("Scenario")) or "Scenario"
        observable = _line(trace.get("Observable consequence"))
        path = _line(trace.get("Control path"))
        lines.append(f"- **{scenario}** — {observable or path or 'See canonical behavior trace.'}")
    return "\n".join(lines).rstrip() + "\n"


def render_qa(model: dict) -> str:
    lines = [
        "# Product intent QA",
        "",
        "> Generated from ProductIntentModel. Verify behavior; do not edit this file to change intent.",
        "",
        "## Must-preserve invariants",
    ]
    must = [item for item in model.get("invariants", []) if item.get("severity") == "must"]
    for inv in must:
        verification = inv.get("verification") or "verification not yet bound"
        lines.append(f"- [ ] **{inv['id']}** — {inv.get('statement', '')}  ")
        lines.append(f"  Verification: {verification}")
    if not must:
        lines.append("- No MUST invariants recorded.")
    lines += ["", "## Acceptance tests"]
    tests = model.get("verification", {}).get("acceptance_tests", [])
    for item in tests:
        lines.append(f"- [ ] {item}")
    if not tests:
        lines.append("- No executable-breadboard acceptance tests were found.")
    lines += ["", "## Behavior traces"]
    for trace in model.get("selected_design", {}).get("behavior_traces", []):
        scenario = _line(trace.get("Scenario")) or "Scenario"
        result = _line(trace.get("Observable consequence")) or "observable result not recorded"
        lines.append(f"- [ ] {scenario}: {result}")
    return "\n".join(lines).rstrip() + "\n"


def render_agent_context(model: dict) -> str:
    lines = [
        "# Product intent context",
        "",
        "Use this as a compact projection of accepted intent. If it conflicts with an owning planning artifact, stop and repair/regenerate the model.",
        "",
        f"- Selected shape: {model.get('selected_design', {}).get('shape') or '—'}",
        f"- Active slice: {model.get('selected_design', {}).get('active_slice') or '—'}",
        "",
        "## Must preserve",
    ]
    for inv in model.get("invariants", []):
        if inv.get("severity") == "must":
            lines.append(f"- {inv['id']}: {inv.get('statement', '')}")
    lines += ["", "## Accepted requirements"]
    for req in model.get("requirements", []):
        lines.append(f"- {req['id']}: {req.get('statement', '')}")
    lines += ["", "## Implementation bindings"]
    for binding in model.get("implementation_bindings", []):
        refs = ", ".join(binding.get("intent_refs", []))
        paths = ", ".join(binding.get("paths", []))
        lines.append(f"- {binding['id']}: {refs} -> {paths}")
    lines += ["", "## Do not do"]
    lines += [
        "- Do not treat rejected alternatives as active scope.",
        "- Do not weaken an invariant to fit the implementation.",
        "- Do not let a refactor silently become a product decision.",
        "- Propose an intent delta and return to planning when accepted behavior needs to change.",
    ]
    return "\n".join(lines).rstrip() + "\n"


def render_support(model: dict) -> str:
    lines = [
        "# Product behavior reference",
        "",
        "> Generated from accepted product intent for support and internal explanation.",
        "",
        "## What users can do",
    ]
    found = False
    for row in model.get("selected_design", {}).get("ui_affordances", []):
        uid = _line(row.get("ID"))
        affordance = _line(row.get("Affordance"))
        place = _line(row.get("Place"))
        if uid and affordance:
            found = True
            lines.append(f"- **{uid}** — {affordance}" + (f" ({place})" if place else ""))
    if not found:
        lines.append("- No user-facing affordances recorded.")
    lines += ["", "## Important behavior"]
    for trace in model.get("selected_design", {}).get("behavior_traces", []):
        scenario = _line(trace.get("Scenario"))
        outcome = _line(trace.get("Observable consequence"))
        if scenario or outcome:
            lines.append(f"- {scenario or 'Scenario'}: {outcome or 'See canonical trace.'}")
    return "\n".join(lines).rstrip() + "\n"


def render_all(model: dict) -> dict[str, str]:
    return {
        "product-behavior.md": render_behavior(model),
        "qa-plan.md": render_qa(model),
        "agent-context.md": render_agent_context(model),
        "support-reference.md": render_support(model),
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--intent", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, required=True)
    args = parser.parse_args(argv)
    model = json.loads(args.intent.read_text(encoding="utf-8"))
    if model.get("kind") != "ProductIntentModel":
        raise SystemExit("Expected a ProductIntentModel")
    args.out_dir.mkdir(parents=True, exist_ok=True)
    for name, content in render_all(model).items():
        (args.out_dir / name).write_text(content, encoding="utf-8")
    print(args.out_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
